CREATE TABLE currencies (
    code CHAR(3) NOT NULL,
    numeric_code INT NOT NULL,
    name_uk VARCHAR(128) NOT NULL,
    name_en VARCHAR(128) NULL,
    nbu_units INT NOT NULL DEFAULT 1,
    minor_units TINYINT NOT NULL DEFAULT 2,
    is_active BOOLEAN NOT NULL DEFAULT FALSE,
    display_order INT NULL,
    PRIMARY KEY (code),
    KEY idx_currencies_active_order (is_active, display_order, code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO currencies (code, numeric_code, name_uk, name_en, nbu_units, minor_units, is_active, display_order) VALUES
('UAH', 980, 'Гривня', 'Hryvnia', 1, 2, TRUE, 0),
('USD', 840, 'Долар США', 'US Dollar', 1, 2, TRUE, 10),
('EUR', 978, 'Євро', 'Euro', 1, 2, TRUE, 20),
('GBP', 826, 'Фунт стерлінгів', 'Pound Sterling', 1, 2, TRUE, 30),
('CHF', 756, 'Швейцарський франк', 'Swiss Franc', 1, 2, TRUE, 40),
('PLN', 985, 'Злотий', 'Zloty', 1, 2, TRUE, 50),
('AUD', 36, 'Австралійський долар', 'Australian Dollar', 1, 2, FALSE, NULL),
('AZN', 944, 'Азербайджанський манат', 'Azerbaijani Manat', 1, 2, FALSE, NULL),
('BDT', 50, 'Така', 'Taka', 1, 2, FALSE, NULL),
('CAD', 124, 'Канадський долар', 'Canadian Dollar', 1, 2, FALSE, NULL),
('CNY', 156, 'Юань Женьміньбі', 'Yuan Renminbi', 1, 2, FALSE, NULL),
('CZK', 203, 'Чеська крона', 'Czech Koruna', 1, 2, FALSE, NULL),
('DKK', 208, 'Данська крона', 'Danish Krone', 1, 2, FALSE, NULL),
('DZD', 12, 'Алжирський динар', 'Algerian Dinar', 1, 2, FALSE, NULL),
('EGP', 818, 'Єгипетський фунт', 'Egyptian Pound', 1, 2, FALSE, NULL),
('GEL', 981, 'Ларі', 'Lari', 1, 2, FALSE, NULL),
('HKD', 344, 'Гонконгівський долар', 'Hong Kong Dollar', 1, 2, FALSE, NULL),
('HUF', 348, 'Форинт', 'Forint', 100, 2, FALSE, NULL),
('IDR', 360, 'Рупія', 'Rupiah', 1000, 0, FALSE, NULL),
('ILS', 376, 'Новий ізраїльський шекель', 'New Israeli Sheqel', 1, 2, FALSE, NULL),
('INR', 356, 'Індійська рупія', 'Indian Rupee', 1, 2, FALSE, NULL),
('JPY', 392, 'Єна', 'Yen', 100, 0, FALSE, NULL),
('KRW', 410, 'Вона', 'Won', 1000, 0, FALSE, NULL),
('KZT', 398, 'Теньге', 'Tenge', 1, 2, FALSE, NULL),
('LBP', 422, 'Ліванський фунт', 'Lebanese Pound', 1, 2, FALSE, NULL),
('MDL', 498, 'Молдовський лей', 'Moldovan Leu', 1, 2, FALSE, NULL),
('MXN', 484, 'Мексиканське песо', 'Mexican Peso', 1, 2, FALSE, NULL),
('MYR', 458, 'Малайзійський ринггіт', 'Malaysian Ringgit', 1, 2, FALSE, NULL),
('NOK', 578, 'Норвезька крона', 'Norwegian Krone', 1, 2, FALSE, NULL),
('NZD', 554, 'Новозеландський долар', 'New Zealand Dollar', 1, 2, FALSE, NULL),
('RON', 946, 'Румунський лей', 'Romanian Leu', 1, 2, FALSE, NULL),
('RSD', 941, 'Сербський динар', 'Serbian Dinar', 1, 2, FALSE, NULL),
('SAR', 682, 'Саудівський ріял', 'Saudi Riyal', 1, 2, FALSE, NULL),
('SEK', 752, 'Шведська крона', 'Swedish Krona', 1, 2, FALSE, NULL),
('SGD', 702, 'Сінгапурський долар', 'Singapore Dollar', 1, 2, FALSE, NULL),
('THB', 764, 'Бат', 'Baht', 1, 2, FALSE, NULL),
('TND', 788, 'Туніський динар', 'Tunisian Dinar', 1, 3, FALSE, NULL),
('TRY', 949, 'Турецька ліра', 'Turkish Lira', 1, 2, FALSE, NULL),
('AED', 784, 'Дирхам ОАЕ', 'UAE Dirham', 1, 2, FALSE, NULL),
('VND', 704, 'Донг', 'Dong', 10000, 0, FALSE, NULL),
('ZAR', 710, 'Ренд', 'Rand', 1, 2, FALSE, NULL);
