CREATE TABLE country_reference (
    code_alpha2 CHAR(2) NOT NULL,
    code_alpha3 CHAR(3) NOT NULL,
    name_uk VARCHAR(128) NOT NULL,
    name_en VARCHAR(128) NOT NULL,
    name_ru VARCHAR(128) NOT NULL,
    PRIMARY KEY (code_alpha2),
    UNIQUE KEY uk_country_reference_alpha3 (code_alpha3)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO country_reference (code_alpha2, code_alpha3, name_uk, name_en, name_ru) VALUES
('AD', 'AND', 'Андорра', 'Andorra', 'Андорра'),
('AL', 'ALB', 'Албанія', 'Albania', 'Албания'),
('AT', 'AUT', 'Австрія', 'Austria', 'Австрия'),
('BA', 'BIH', 'Боснія і Герцеговина', 'Bosnia and Herzegovina', 'Босния и Герцеговина'),
('BE', 'BEL', 'Бельгія', 'Belgium', 'Бельгия'),
('BG', 'BGR', 'Болгарія', 'Bulgaria', 'Болгария'),
('BY', 'BLR', 'Білорусь', 'Belarus', 'Беларусь'),
('CH', 'CHE', 'Швейцарія', 'Switzerland', 'Швейцария'),
('CY', 'CYP', 'Кіпр', 'Cyprus', 'Кипр'),
('CZ', 'CZE', 'Чехія', 'Czechia', 'Чехия'),
('DE', 'DEU', 'Німеччина', 'Germany', 'Германия'),
('DK', 'DNK', 'Данія', 'Denmark', 'Дания'),
('EE', 'EST', 'Естонія', 'Estonia', 'Эстония'),
('ES', 'ESP', 'Іспанія', 'Spain', 'Испания'),
('FI', 'FIN', 'Фінляндія', 'Finland', 'Финляндия'),
('FR', 'FRA', 'Франція', 'France', 'Франция'),
('GB', 'GBR', 'Велика Британія', 'United Kingdom', 'Великобритания'),
('GR', 'GRC', 'Греція', 'Greece', 'Греция'),
('HR', 'HRV', 'Хорватія', 'Croatia', 'Хорватия'),
('HU', 'HUN', 'Угорщина', 'Hungary', 'Венгрия'),
('IE', 'IRL', 'Ірландія', 'Ireland', 'Ирландия'),
('IS', 'ISL', 'Ісландія', 'Iceland', 'Исландия'),
('IT', 'ITA', 'Італія', 'Italy', 'Италия'),
('LI', 'LIE', 'Ліхтенштейн', 'Liechtenstein', 'Лихтенштейн'),
('LT', 'LTU', 'Литва', 'Lithuania', 'Литва'),
('LU', 'LUX', 'Люксембург', 'Luxembourg', 'Люксембург'),
('LV', 'LVA', 'Латвія', 'Latvia', 'Латвия'),
('MC', 'MCO', 'Монако', 'Monaco', 'Монако'),
('MD', 'MDA', 'Молдова', 'Moldova', 'Молдова'),
('ME', 'MNE', 'Чорногорія', 'Montenegro', 'Черногория'),
('MK', 'MKD', 'Північна Македонія', 'North Macedonia', 'Северная Македония'),
('MT', 'MLT', 'Мальта', 'Malta', 'Мальта'),
('NL', 'NLD', 'Нідерланди', 'Netherlands', 'Нидерланды'),
('NO', 'NOR', 'Норвегія', 'Norway', 'Норвегия'),
('PL', 'POL', 'Польща', 'Poland', 'Польша'),
('PT', 'PRT', 'Португалія', 'Portugal', 'Португалия'),
('RO', 'ROU', 'Румунія', 'Romania', 'Румыния'),
('RS', 'SRB', 'Сербія', 'Serbia', 'Сербия'),
('RU', 'RUS', 'Росія', 'Russia', 'Россия'),
('SE', 'SWE', 'Швеція', 'Sweden', 'Швеция'),
('SI', 'SVN', 'Словенія', 'Slovenia', 'Словения'),
('SK', 'SVK', 'Словакчина', 'Slovakia', 'Словакия'),
('SM', 'SMR', 'Сан-Марино', 'San Marino', 'Сан-Марино'),
('UA', 'UKR', 'Україна', 'Ukraine', 'Украина'),
('VA', 'VAT', 'Ватикан', 'Vatican City', 'Ватикан'),
('XK', 'XKX', 'Косово', 'Kosovo', 'Косово');
