-- Російська назва валюти для довідника currencies.
ALTER TABLE currencies
    ADD COLUMN name_ru VARCHAR(128) NULL AFTER name_en;

UPDATE currencies
SET name_ru = CASE code
    WHEN 'UAH' THEN 'Гривна'
    WHEN 'USD' THEN 'Доллар США'
    WHEN 'EUR' THEN 'Евро'
    WHEN 'GBP' THEN 'Фунт стерлингов'
    WHEN 'CHF' THEN 'Швейцарский франк'
    WHEN 'PLN' THEN 'Злотый'
    WHEN 'AUD' THEN 'Австралийский доллар'
    WHEN 'AZN' THEN 'Азербайджанский манат'
    WHEN 'BDT' THEN 'Така'
    WHEN 'CAD' THEN 'Канадский доллар'
    WHEN 'CNY' THEN 'Юань Женьминьби'
    WHEN 'CZK' THEN 'Чешская крона'
    WHEN 'DKK' THEN 'Датская крона'
    WHEN 'DZD' THEN 'Алжирский динар'
    WHEN 'EGP' THEN 'Египетский фунт'
    WHEN 'GEL' THEN 'Лари'
    WHEN 'HKD' THEN 'Гонконгский доллар'
    WHEN 'HUF' THEN 'Форинт'
    WHEN 'IDR' THEN 'Рупия'
    WHEN 'ILS' THEN 'Новый израильский шекель'
    WHEN 'INR' THEN 'Индийская рупия'
    WHEN 'JPY' THEN 'Иена'
    WHEN 'KRW' THEN 'Вона'
    WHEN 'KZT' THEN 'Тенге'
    WHEN 'LBP' THEN 'Ливанский фунт'
    WHEN 'MDL' THEN 'Молдавский лей'
    WHEN 'MXN' THEN 'Мексиканское песо'
    WHEN 'MYR' THEN 'Малайзийский ринггит'
    WHEN 'NOK' THEN 'Норвежская крона'
    WHEN 'NZD' THEN 'Новозеландский доллар'
    WHEN 'RON' THEN 'Румынский лей'
    WHEN 'RSD' THEN 'Сербский динар'
    WHEN 'SAR' THEN 'Саудовский риял'
    WHEN 'SEK' THEN 'Шведская крона'
    WHEN 'SGD' THEN 'Сингапурский доллар'
    WHEN 'THB' THEN 'Бат'
    WHEN 'TND' THEN 'Тунисский динар'
    WHEN 'TRY' THEN 'Турецкая лира'
    WHEN 'AED' THEN 'Дирхам ОАЭ'
    WHEN 'VND' THEN 'Донг'
    WHEN 'ZAR' THEN 'Рэнд'
    ELSE name_ru
END;
